server:
  port: 8080
spring:
  application:
    #    应用名
    name: Car_Rental_System_4.0
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/car_rental4?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  data:
    mongodb:
#        host: localhost
#        port: 27017
        url: mongodb://localhost:27017/
        database:
          CRS4: CRS4
          CarRental3Mongodb: CarRental3Mongodb

  redis:
    host: localhost
    port: 6379
    database: 4


  mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/



